### ISSUE TITLE
Crash on shearing

### ISSUE THREAD

**Issue by aurilisdev** [lehjr/MachineMusePowersuits#11]
java.lang.NullPointerException: Ticking entity
	at net.minecraft.stats.Stat.func_197919_a(SourceFile:29) ~[?:?] {re:classloading}
	at net.minecraft.stats.Stat.func_197918_a(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.stats.Stat.<init>(SourceFile:16) ~[?:?] {re:classloading}
	at net.minecraft.stats.StatType.func_199075_a(StatType.java:31) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.Map.computeIfAbsent(Map.java:1003) ~[?:?] {}
	at net.minecraft.stats.StatType.func_199077_a(StatType.java:30) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.stats.StatType.func_199076_b(StatType.java:44) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.PlayerEntity.func_195066_a(PlayerEntity.java:1444) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimapfair:xaero_playerentity_iswearing,pl:runtimedistcleaner:A}
	at com.github.lehjr.powersuits.item.module.tool.ShearsModule$CapProvider$BlockBreaker.onBlockDestroyed(ShearsModule.java:145) ~[powersuits:1.16.4-2.0.4] {re:classloading}
	at com.github.lehjr.powersuits.item.tool.PowerFist.lambda$null$0(PowerFist.java:78) ~[powersuits:1.16.4-2.0.4] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:213) ~[forge:?] {re:classloading}
	at com.github.lehjr.powersuits.item.tool.PowerFist.lambda$onBlockDestroyed$1(PowerFist.java:76) ~[powersuits:1.16.4-2.0.4] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:213) ~[forge:?] {re:classloading}
	at com.github.lehjr.powersuits.item.tool.PowerFist.func_179218_a(PowerFist.java:73) ~[powersuits:1.16.4-2.0.4] {re:classloading}
	at net.minecraft.item.ItemStack.func_179548_a(ItemStack.java:380) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:316) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_73075_a(PlayerInteractionManager.java:110) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70071_h_(ServerPlayerEntity.java:484) ~[?:?] {re:classloading,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:720) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:736) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:493) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1016) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:930) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:765) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:277) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}

**Comment by lehjr** [comment]
fixed quite awhile ago
